name: Metrics

on:
  schedule: [{ cron: "0 6 * * *" }]  # 06:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          template: classic
          base: header, activity
          config_timezone: Europe/Paris

          # Langages (section compacte, 6 max pour rester clean)
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 6
          plugin_languages_ignored: html, css

          # Commit automatique du SVG à la racine
          output_action: commit
          committer_branch: main
          committer_message: "chore: update metrics"
